darint916/Chord-KTV

- .github/workflows/dotnet-build-run-check.yml
- ChordKTV/Controllers/SongController.cs
- ChordKTV/README.md
- ChordKTV/appsettings.json
Should allow for a build and run pipeline, also added controller endpoint to return API health. 
Fixes #13 
Need more sophisticated checks later.
> GitHub actions build run dotnet

- ChordKTV/Controllers/SongController.cs
- ChordKTV/Services/Api/IChatGptService.cs
- ChordKTV/Services/Api/IGeniusService.cs
- ChordKTV/Services/Api/ILrcService.cs
- ChordKTV/Services/Api/IYouTubeService.cs
- ChordKTV/Services/Service/ChatGptService.cs
- ChordKTV/Services/Service/GeniusService.cs
- ChordKTV/Services/Service/LrcService.cs
- ChordKTV/Services/Service/YouTubeClientService.cs
- ChordKTV/Utils/SafeEnumConverter.cs
Naming routes for API to follow closer to REST convention and cleans up using directives.
Fixes #
> Backend rest api controller refactor

- .github/ISSUE_TEMPLATE/bug-report🐛-.md
- .github/ISSUE_TEMPLATE/✨feature-request.md
> Update issue templates

- frontend/lyric-sync-app/package-lock.json
- frontend/lyric-sync-app/package.json
- frontend/lyric-sync-app/src/App.tsx
- frontend/lyric-sync-app/src/components/AppBarComponent.tsx
- frontend/lyric-sync-app/src/components/HandwritingCanvas.tsx
- frontend/lyric-sync-app/src/pages/HandwritingPage.tsx
- frontend/lyric-sync-app/src/pages/SongPlayerPage.tsx
Adds a component that accepts user handwriting input using React HTML5 canvas. Returns data is base-64 formatted .png
Fixes #40
Handwriting Canvas page:
> Handwriting Canvas Input

- ChordKTV/ChordKTV.csproj
- ChordKTV/Program.cs
Logging for production and save to file + console (local). Uses serilog
Fixes #21
> logging added

- ChordKTV/Controllers/SongController.cs
- ChordKTV/Services/Api/IYouTubeClientService.cs
- ChordKTV/Services/Service/YouTubeClientService.cs
- ChordKTV/Utils/Shuffle.cs
Fisher Yates shuffle on youtube playlist endpoint. Shuffle boolean option added
Fixes #56
> fisher yates shuffle

- ChordKTV/Controllers/SongController.cs
- ChordKTV/Data/Api/SongData/ISongRepo.cs
- ChordKTV/Data/Repo/SongData/SongRepo.cs
- ChordKTV/Dtos/FullSong/FullSongRequestDto.cs
- ChordKTV/Program.cs
- ChordKTV/Services/Api/IFullSongService.cs
- ChordKTV/Services/Service/FullSongService.cs
- ChordKTV/Services/Service/GeniusService.cs
- ChordKTV/Utils/KeywordExtractorUtils.cs
Adding lyrics search functionality, making the search more robust, if genius fails uses user input instead of lrc. Basically maximizing search chances.
Added album input option too.
Filled in the song DTO and title/artist alternates and Ids ect.
Fixes #33 
someone has the artist on lrc..
Use custom utube channels that send out lyric videos (unofficial vids)
Do we need to address issues with dupes in our database? i think it is fine?
> Backend integration lyrics implementation

- ChordKTV/Services/Service/GeniusService.cs
When searching for "Close to you" by "Carpenters", the service was:
1. Not finding the correct song ("They Long to Be [Close to You]" by Carpenters)
2. Sometimes returning incorrect matches (e.g., Frank Ocean's version)
3. Being too strict with partial artist matches
4. Using quoted searches that were too restrictive
- Added substring matching for titles
- Set a reasonable minimum title score threshold (50)
- Boosted scores for titles that contain the search query
```csharp
bool containsTitle = normalizedResultTitle.Contains(normalizedQueryTitle, StringComparison.OrdinalIgnoreCase);
int titleScore = containsTitle ? Math.Max(exactTitleScore, 85) : exactTitleScore;
```
- Made artist matching optional and used only for ranking
- Removed strict artist score requirements
- Artist score now …
> improved genius search /search endpoint

- frontend/lyric-sync-app/package-lock.json
- frontend/lyric-sync-app/package.json
- frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.scss
- frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.tsx
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.scss
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Added auto-scrolling to lyrics and highlighting. Will autoscroll when play is hit or when changing timestamp, also if user scrolls during pause, it will auto lock on in 3 seconds of inactive scroll.
Fixes #53 
Needs redesign to style, out of scope of functionality opened #95
> Frontend scrollable lyrics

- ChordKTV/Services/Api/IGeniusService.cs
- ChordKTV/Services/Service/FullSongService.cs
- ChordKTV/Services/Service/GeniusService.cs
Fix gpt constant call not pulling caches for romanization. Enrich Genius metadata reintegrated, and nullability fix. No useless gpt calls for english song alr translated
Fixes #102 
Addresses ending translation concern in #104
> backend logic fix and simplificiation for gpt transl + rom

- ChordKTV/Dtos/FullSong/FullSongResponseDto.cs
- ChordKTV/Services/Service/FullSongService.cs
Added duration to full integration endpoint (based on LRC synced)
Fixes #98
> Backend duration adding

- ChordKTV/Dtos/OpenAI/CandidateSongInfo.cs
- ChordKTV/Dtos/OpenAI/CandidateSongInfoListResponse.cs
- ChordKTV/Dtos/SongDto.cs
- ChordKTV/README.md
- ChordKTV/Services/Api/IChatGptService.cs
- ChordKTV/Services/Service/ChatGptService.cs
- ChordKTV/Services/Service/FullSongService.cs
- ChordKTV/Utils/TextUtils.cs
- README.md
As a last effort to search using complex youtube titles for the endpoint, since we have titles (as seen in the issue) that contain a lot of fluff that can't be easily caught and filtered out by our search functions, we use gpt to create a candidate list of title artist combinations that are also in separated in different languages, since some artists can have names in multiple languages and songs can have different language titles all in one youtube video title. Also made a small bug fix that uses youtube data or lrc lib or user input to replace genius if we can't get accurate query on LRC using genius parameters
Fixes #107 
Fixes #18 
Trying this video with a convoluted title, previously failed LRC now successfully queries 
Another song:
```
{
"title": null,
"artist": null,
"album": …
```
> Backend gpt remedial query extraction

- frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
Adds frontend input boxes for lyrics and YT URL for full song endpoint
> Add extra boxes for lyrics, yt url

- ChordKTV/Controllers/HandwritingController.cs
- ChordKTV/Controllers/UserController.cs
- ChordKTV/Data/Api/SongData/ISongRepo.cs
- ChordKTV/Data/AppDbContext.cs
- ChordKTV/Data/Repo/QuizData/QuizRepo.cs
- ChordKTV/Data/Repo/SongData/AlbumRepo.cs
- ChordKTV/Data/Repo/SongData/SongRepo.cs
- ChordKTV/Dtos/HandwritingCanvas/HandwritingCanvasRequestDto.cs
- ChordKTV/Dtos/HandwritingCanvas/HandwritingCanvasResponseDto.cs
- ChordKTV/Dtos/SongDto.cs
- ChordKTV/Dtos/VideoInfo.cs
- ChordKTV/Models/SongData/Album.cs
- ChordKTV/Models/SongData/GeniusMetaData.cs
- ChordKTV/Models/SongData/Song.cs
- ChordKTV/Models/UserData/User.cs
- ChordKTV/Profiles/FullSongProfile.cs
- ChordKTV/Profiles/QuizProfile.cs
- ChordKTV/Profiles/SongProfile.cs
- ChordKTV/Program.cs
- ChordKTV/Services/Api/IHandwritingService.cs
- ChordKTV/Services/Api/IQuizService.cs
- ChordKTV/Services/Service/ChatGptService.cs
- ChordKTV/Services/Service/HandwritingService.cs
- ChordKTV/Services/Service/QuizService.cs
- ChordKTV/Utils/CompareUtils.cs
- ChordKTV/Utils/KeywordExtractorUtils.cs
- ChordKTV/Utils/Shuffle.cs
remove unnecessary imports and fix namespacing
Fixes #
> import cleanup + spacing

- ChordKTV/Dtos/LrcLyricsDto.cs
- ChordKTV/Services/Service/FullSongService.cs
- ChordKTV/Services/Service/LrcService.cs
Reverts darint916/Chord-KTV#85
> Revert "LRCSearch: Add Artist and Title Alternates to Return DTO"

- ChordKTV/Data/Api/SongData/IGeniusMetaDataRepo.cs
- ChordKTV/Data/Api/SongData/ISongRepo.cs
- ChordKTV/Data/Repo/SongData/GeniusMetaDataRepo.cs
- ChordKTV/Data/Repo/SongData/SongRepo.cs
- ChordKTV/Dtos/SongDto.cs
- ChordKTV/Program.cs
- ChordKTV/Services/Service/GeniusService.cs
Created New Repository for GeniusMetaData
Created IGeniusMetaDataRepo interface
Implemented GeniusMetaDataRepo class
Moved all GeniusMetaData operations from SongRepo to the new repository
Modified SongDto to more closely match the Song entity model
Added explicit Id mapping in the profile
All endpoints were tested and are functioning as expected.
Fixes #46
> Reapply Fixed GeniusMetaData Repository Refactoring

- .github/workflows/pr-description-validation.yml
circumvent dependabot pr summary check
Fixes #
> depend clause

- .editorconfig
- ChordKTV/Services/Service/ChatGptService.cs
JSON Fixing for GPT translation. Enforces escaped quotes
Extend fix on #113 
Previously failing:
Now works:
> Unescape Quotes checker

- ChordKTV/Services/Service/ChatGptService.cs
- ChordKTV/Services/Service/FullSongService.cs
- ChordKTV/Services/Service/GeniusService.cs
- frontend/lyric-sync-app/src/components/YouTubePlayer/YouTubePlayer.tsx
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Recursion error exceeding max depth was due to rendering every ms of the time provided by the video which triggered a dom rerender, costing a lot of resources. Now it uses animation frame API to check monitor refreshrate, then along that, checks if the current time actually changed in terms of LRC segment frames, and if so then does the rerender, which only occurs at every line of the lyrics. So much more efficient. Also added youtube autoplay
Also minor edits to backend gpt catching edge cases + error logs + lyric search fix
Fixes #174
> framechecking and efficient rerendering for youtube player

- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.scss
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Allow user to use slider on frontend to add an offset to the LRC display, to sync with YT video.
Fixes #124
> Add offset slider on frontend

- ChordKTV/Services/Service/YouTubeClientService.cs
Tried to get the MV/official video when searching so it is clean.
Fixes #
Originally was getting a lyric video
> youtube better vid

- ChordKTV/Services/Service/ChatGptService.cs
- ChordKTV/Services/Service/FullSongService.cs
- ChordKTV/Services/Service/LrcService.cs
- ChordKTV/Services/Service/YouTubeClientService.cs
- frontend/lyric-sync-app/src/components/LyricDisplay/LyricDisplay.tsx
- frontend/lyric-sync-app/src/components/QueueComponent/QueueComponent.scss
- frontend/lyric-sync-app/src/components/QueueComponent/QueueComponent.tsx
- frontend/lyric-sync-app/src/components/YouTubePlayer/YouTubePlayer.tsx
- frontend/lyric-sync-app/src/pages/HandwritingPage/HandwritingPage.tsx
- frontend/lyric-sync-app/src/pages/HomePage/HomePage.tsx
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.scss
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Fixes remaining Done By Final issues along with bugs found in final testing. In Person meetup for stress testing and small fixes + features.
Added Features
- Shuffle button that shuffles future queue
- Autoplay button to quick go next
- 
Improvements
- Gpt backend model improvement + more specific prompt (still has issue)
- Genius Language Code fixed up by lyrics (should match now), previously was not being saved
- Force Romanization from GPT to avoid parsing errors (need to have better detection filter later on (find like rom or eng in title))
- Duration tolerance on ktv vids and main utube search (from the merge)
- Slider time adjustments and resets
- Better Error Codes
- Songs not playing on load
Fixes #210, #193, #167, #139, #122
> Miscellaneous fixes before final presentation

- ChordKTV/Services/Service/ChatGptService.cs
- frontend/lyric-sync-app/src/pages/SongPlayerPage/SongPlayerPage.tsx
Song lyric fixes for many songs. Redid romanization and translation prompts (split and parallelized), cut down time by ~40%?
NOTE: comments left in frontend for debugging line skip issue 
Some of these issues were fixed in previous prs unnoticed, but confirmed in this pr to be fixed
Fixes #199 Fixes #192 
Lyrics found:
Song Lyrics found:
Search works now:
Missing lyrics romanized properly:
Incorrect lyrics romanized properly:
Prev artist not found:
> Song search fixes prompts
